steps:
  - name: build container image
    when:
      - event: push
      - event: cron
      - event: manual
    image: quay.io/containers/podman
    privileged: true
    secrets: [ "FORGEJO_PACKAGES_ACCESS", "GITHUB_PACKAGES_ACCESS" ]
    commands:
      - podman build . -t mailcalf
      - podman save -o mailcalf.tar mailcalf

  - name: publish container image
    when:
      - event: manual
        branch: main
      - event: push
        branch: main
      - event: cron
        cron: periodic-rebuild
    image: quay.io/containers/skopeo
    secrets: [ "FORGEJO_PACKAGES_ACCESS", "GITHUB_PACKAGES_ACCESS" ]
    commands:
      - skopeo copy --dest-username ftsell --dest-password $FORGEJO_PACKAGES_ACCESS docker-archive:mailcalf.tar docker://git.lly.sh/ftsell/mailcalf
      - skopeo copy --dest-username ftsell --dest-password $GITHUB_PACKAGES_ACCESS docker-archive:mailcalf.tar docker://ghcr.io/ftsell/mailcalf
